dist: xenial
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst apertium lttoolbox apertium-dev lttoolbox-dev libhfst-dev cg3
script:
    - ./autogen.sh
    - ./configure
    - make
    - make check
notifications:
    irc:
        channels:
            - "irc.oftc.net#omorfi"
            - "irc.oftc.net#apertium"
        on_failure: change
        on_success: never

